//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLOOD_BANK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blood_Table_1
    {
        public string Blood_Group { get; set; }
        public int B_Stock { get; set; }
    }
}
