//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLOOD_BANK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blood_Transfer_Table
    {
        public int T_Num { get; set; }
        public string P_Name { get; set; }
        public string B_Group { get; set; }
    }
}
