//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLOOD_BANK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Table
    {
        public int Emp_Num { get; set; }
        public string Emp_Id { get; set; }
        public string Emp_Pass { get; set; }
    }
}
