//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLOOD_BANK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Blood_Bank_Management_SystemEntities : DbContext
    {
        public Blood_Bank_Management_SystemEntities()
            : base("name=Blood_Bank_Management_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blood_Table_1> Blood_Table_1 { get; set; }
        public virtual DbSet<Blood_Transfer_Table> Blood_Transfer_Table { get; set; }
        public virtual DbSet<Donor_Table_1> Donor_Table_1 { get; set; }
        public virtual DbSet<Employee_Table> Employee_Table { get; set; }
        public virtual DbSet<Patient_Table_1> Patient_Table_1 { get; set; }
        public virtual DbSet<Transfer_Table> Transfer_Table { get; set; }
    }
}
