//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLOOD_BANK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Table_1
    {
        public int P_Num { get; set; }
        public string P_Name { get; set; }
        public int P_Age { get; set; }
        public string P_Phone { get; set; }
        public string P_Gender { get; set; }
        public string P_Blood_Group { get; set; }
        public string P_Address { get; set; }
    }
}
